Increase image build timeout
Recent jobs failed because of:

```
Your build timed out. Use the [--timeout=DURATION] flag to change the timeout threshold.
ERROR: (gcloud.builds.submit) build 8de00cd3-b54d-4ffc-be1c-334e880f885e completed with status "TIMEOUT"
```
https://storage.googleapis.com/kubernetes-jenkins/logs/post-cri-tools-images/1382513971000512512/build-log.txt

We now increase the timeout to be able to run the job completely.

Signed-off-by: Sascha Grunert <sgrunert@redhat.com>